name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint-and-format:
    name: ğŸ” Lint & Format
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [22.21.1, 24.11.1]
    
    steps:
      - name: ğŸ“¥ Checkout
        uses: actions/checkout@v6

      - name: ğŸ”§ Setup Project
        uses: ./.github/actions/setup
        with:
          node-version: ${{ matrix.node-version }}

      - name: ğŸ› ï¸ Setup Biome
        uses: biomejs/setup-biome@v2
        with:
          version: latest

      - name: ğŸ” Run Biome CI
        run: biome ci .

      - name: ğŸ” Run lint
        run: npm run lint

  type-check:
    name: ğŸ”§ Type Check
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [22.21.1, 24.11.1]
    
    steps:
      - name: ğŸ“¥ Checkout
        uses: actions/checkout@v5

      - name: ğŸ”§ Setup Project
        uses: ./.github/actions/setup
        with:
          node-version: ${{ matrix.node-version }}

      - name: ğŸ± Run TypeScript compiler
        run: npx tsc --noEmit

  test:
    name: ğŸ§ª Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [22.21.1, 24.11.1]

    steps:
      - name: ğŸ“¥ Checkout
        uses: actions/checkout@v5

      - name: ğŸ”§ Setup Project
        uses: ./.github/actions/setup
        with:
          node-version: ${{ matrix.node-version }}

      - name: ğŸ§ª Run tests
        run: npm test

  build:
    name: ğŸ—ï¸ Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [22.21.1, 24.11.1]
    
    steps:
      - name: ğŸ“¥ Checkout
        uses: actions/checkout@v5

      - name: ğŸ”§ Setup Project
        uses: ./.github/actions/setup
        with:
          node-version: ${{ matrix.node-version }}

      - name: ğŸ—ï¸ Build package
        run: npm run build
